version: '3.7'
services:
    nginx:
        build:
            context: './docker/nginx'
            dockerfile: Dockerfile
        container_name: laravel-nginx
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/nginx/sites:/etc/nginx/sites-available
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php-fpm
        networks:
            - sail

    php-fpm:
        build:
            context: './docker/php-fpm'
            dockerfile: Dockerfile
        container_name: laravel-php
        restart: unless-stopped
        volumes:
            - ./:/var/www
        expose:
            - '9000'
        depends_on:
            - mariadb
        networks:
            - sail

    mariadb:
        image: 'mariadb:10'
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER: '${DB_USERNAME}'
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - 3306:3306
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    mariadb_data:
        driver: local
